### ISSUE TITLE
словарик новичка

### ISSUE THREAD

**Issue by stsypanov** [phplego/kotlin.su#4]
Возможно стоит добавить на страницу словарик для новичков, ранее не работавших с Java или другим ЯП, и добавить туда определения вроде DTO, POJO и т.п?

Кстати, POCO - это plain old Kotlin object? Если да, то, возможно, стоит писать POKO вместо POCO?

**Comment by phplego** [comment]
Я как раз сейчас делаю возможность редактировать меню через через Github.
Просто вынесу структуру меню в отдельный файл в каком-нибудь формате, чтобы
можно было добавлять разделы/страницы.

А по поводу POCO, насколько я понимаю, это Plain Old Class Object (source:
http://stackoverflow.com/questions/725348/poco-vs-dto)


20 февраля 2016 г., 22:36 пользователь Sergei Tsypanov <
notifications@github.com> написал:

**Comment by phplego** [comment]
Я кстати вам доступ дал, чтобы вы могли коммитить в репозиторий напрямую, без необходимости создавать Pull Request

**Comment by stsypanov** [comment]
отлично, спасибо!

**Comment by rcd27** [comment]
Мне бы такой доступ тоже не помешал.
