### ISSUE TITLE
добавить ссылки на канал Devcolibri

### ISSUE THREAD

**Issue by stsypanov** [phplego/kotlin.su#5]
Ребята делают видеоуроки о Kotlin. Уже 2 загрузили, было бы неплохо добавить на страничку.

Урок 0: https://www.youtube.com/watch?v=L9k_NdTaMeI
Урок 1: https://www.youtube.com/watch?v=frw1DpNm_ms

**Comment by phplego** [comment]
Мне кажется в документации это будет немного неуместно
