### ISSUE TITLE
Закончен раздел "Основные типы"

### ISSUE THREAD

**Issue by stsypanov** [phplego/kotlin.su#6]
попробуйте обновить страничку, посмотрим, что получилось

**Comment by phplego** [comment]
Обновил. Супер!

**Comment by phplego** [comment]
Кстати само название пункта меню берется из этого же файла, его тоже можно переводить

**Comment by phplego** [comment]
А еще для выгрузки можно использовать ссылку http://kotlin.su/update.php

**Comment by stsypanov** [comment]
Похоже, что ссылка, которую вы указали для выгрузки, перестала работать. Вижу такое сообщение:



*** UPDATING REFERENCE ...
error: insufficient permission for adding an object to repository database .git/objects
Cannot save the current index state
Already up-to-date.
error: Your local changes to the following files would be overwritten by merge:
	config/db.php
	yii
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by phplego** [comment]
Поправил :)

**Comment by stsypanov** [comment]
Спасибо, работает
