### ISSUE TITLE
Ссылка на раздел higher-order-functions ведет на несуществующий файл

### ISSUE THREAD

**Issue by phplego** [phplego/kotlin.su#9]
@rcd27 Ссылка на раздел higher-order-functions ведет на несуществующий файл

![image](https://cloud.githubusercontent.com/assets/3162688/22755440/3768fd14-ee54-11e6-8f25-c626fbbf0a4f.png)

**Comment by rcd27** [comment]
Файл был на пулл реквесте. Сейчас всё в порядке. Спасибо за добавление. Буду переводить потихоньку, так как изучаю этот язык.
